version: '3.9'

services:
  db:
    image: mysql
    container_name: cinema_booking_mysql
    restart: always
    ports:
      - "3333:3306"
    volumes:
      - db_volume:/var/lib/mysql
      - ./scripts/database:/docker-entrypoint-initdb.d/:ro
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cinema_booking

  redis:
    container_name: cinema_booking_redis
    image: bitnami/redis
    ports:
      - "6333:6379"
    environment:
      REDIS_REPLICATION_MODE: master
      ALLOW_EMPTY_PASSWORD: yes
volumes:
  db_volume:
