version: '3.9'

services:
  db:
    image: mysql
    container_name: cinema_booking_mysql
    restart: always
    ports:
      - "3333:3306"
    volumes:
      - db_volume:/var/lib/mysql
      - ./scripts/database:/docker-entrypoint-initdb.d/:ro
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cinema_booking
    networks:
      - cinema_net


  redis:
    container_name: cinema_booking_redis
    image: bitnami/redis
    ports:
      - "6333:6379"
    environment:
      REDIS_REPLICATION_MODE: master
      ALLOW_EMPTY_PASSWORD: yes
    networks:
      - cinema_net


  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./config/dev.yml:/app/config/local.yml
    depends_on:
      - db
      - redis
    networks:
      - cinema_net

  frontend:
    build:
      context: ./fe
    ports:
      - "3000:80"
    volumes:
      - ./fe:/app
    depends_on:
      - backend
    networks:
      - cinema_net

networks:
  cinema_net:
    driver: bridge

volumes:
  db_volume:
